\ir 00_core_schema.sql
\ir 01_seed_shared_courses.sql
\ir 02_seed_majors.sql
\ir majors/anthoropology.sql
\ir majors/arthistory.sql
\ir majors/biology.sql
\ir majors/biochem.sql
\ir majors/chemistry.sql
\ir majors/chinese.sql
\ir majors/computerscience.sql
\ir majors/economics.sql
\ir majors/english.sql
\ir majors/french.sql
\ir majors/gwss.sql
\ir majors/history.sql
\ir majors/japanese.sql
\ir majors/math.sql
\ir majors/physics.sql
\ir majors/political.sql
\ir majors/psychology.sql
\ir majors/sociology.sql
