\ir 00_core_schema.sql
\ir 01_seed_shared_courses.sql
\ir majors/biology.sql
\ir majors/biochem.sql
\ir majors/computerscience.sql
\ir majors/economics.sql
\ir majors/math.sql
\ir majors/political.sql
\ir majors/psychology.sql
\ir majors/sociology.sql
